; (c) 2017 Technische Universität Berlin
; (c) 2024 Tampere University
;
; This software is licensed under GNU General Public License version 3 or later.
;
; For the full copyright and license information, 
; please see https://www.gnu.org/licenses/gpl-3.0.html or read 
; the LICENSE.txt file that was distributed with this source code.

htmlTitle = Muuntaja
headline = Tampereen yliopiston PDF/A-muuntaja
introduction = "Muuntaja on www-palvelu, jonka avulla voit muuntaa tavallisen PDF-tiedoston <a href="https://libguides.tuni.fi/opinnaytteet/pdfa">PDF/A-dokumentiksi</a>. PDF/A-tiedosto on pitkäaikaissäilytykseen ja arkistointiin tarkoitettu tiedostomuoto."

navButton[] = Etusivu,,glyphicon-home
navButton[] = Ohje,help.php,glyphicon-question-sign


selectFile = Valitse ladattava PDF-tiedosto:
uploadFile = Lataa
browse = Selaa

uploadedFile = Olet ladannut seuraavan tiedoston:
processComment = Valitse käsittelytyyppi.
deleteMessage = Kun olet ladannut muunnetun tiedoston, poista se palvelimelta.
deleteButton = Poista
downloadLabel = Lataa muunnettu tiedosto
downloadButton = Lataa
pdfaValidateMessage = Validoi PDF/A-muotoon:
pdfaConvertMessage = Muunna PDF/A-muotoon:
pdfaMetadataMessage = "Nämä tiedot näkyvät muunnetun tiedoston Dokumentin ominaisuudet -kohdassa. Uudet kuvailutiedot korvaavat aiemmat dokumentin kuvailutiedot. Jos jätät kentän tyhjäksi, aiemmat dokumentin kuvailutiedot jäävät tiedostoon."

failMessage = "Tiedostoa ei voitu muuntaa. Ota yhteyttä osoitteeseen thesis@tuni.fi."
okMessage = "Muunnos onnistui"

validateButton = Validointi
convertButton = Muunna
conversionIdle = Muunnosta odotetaan.
conversionInProgress = "Muunnos käynnissä. Voit ladata tiedoston, kun se valmistuu."
conversionSuccess = "Muunnos onnistui. Muokattu tiedosto on ladattavissa."
conversionFailed = "Muunnos epäonnistui. Ota yhteyttä osoitteeseen tuni@tuni.fi."

creatorLabel = "Tekijä(t), eroteltuna ';' merkillä"
titleLabel = Otsikko
keywordsLabel = "Avainsanat eroteltuna ';' merkillä"
descriptionLabel = Kuvaus

pdfaProcessType[] = --analyze,Validate
pdfaProcessType[] = ,Convert

pdfaLevel[] = 1b
pdfaLevel[] = 1a
pdfaLevel[] = 2b
pdfaLevel[] = 2a
pdfaLevel[] = 3b
pdfaLevel[] = 3a
pdfaLevel[] = 3u

pdfaModus[] = ,Vakio
pdfaModus[] = "--forceconversion_reconvert,Uudelleenkonversio"
pdfaModus[] = "--forceconversion_pagestoimages,Ongelmalliset sivut"
pdfaModus[] = "--forceconversion_doctoimages,Kaikki sivut"

fileNotChosen = "Valitse PDF-tiedosto."
fileNotSaved = Tapahtui virhe: ladattua tiedostoa ei voitu tallentaa. Yritä uudelleen.
xmpFileNotSaved = Tapahtui virhe: metadataa sisältävää tiedostoa ei voitu tallentaa, metadataa ei lisätty PDF-dokumenttiin.
fileNotFound = Tapahtui virhe: ladattu tiedosto puuttuu. Yritä uudelleen.
fileAlreadyExists = "Tapahtui virhe: tiedosto on jo olemassa. Yritä uudelleen."
fileDeletedMessage = "Tiedosto poistettiin."
fileTooLarge = "Tiedosto on liian suuri muunnettavaksi. Ota yhteyttä osoitteeseen thesis@tuni.fi."
returnValueMessage = Yksityiskohdat:
uploadNoPdf = Voit ladata vain PDF-tiedostoja.
downloadFileNotExists = Tapahtui virhe: tiedosto puuttuu.

imprint = Tietoa palvelusta
contact = Ota yhteyttä
privacy = Tietosuojaseloste

imprint_link = https://www.tu-berlin.de/servicemenue/impressum/
contact_link = "https://surveys.tuni.fi/lime/137772?lang=fi"
privacy_link = https://www.tu-berlin.de/allgemeine_seiten/datenschutz/parameter/en/
logo_link = https://tuni.fi/kirjasto
logo_image = images/TAUfi_logo.png

helpHeadline = "PDF/A-muuntaja"
helpIntroduction = "Muuntaja on www-palvelu, jonka avulla voit muuntaa tavallisen PDF-tiedoston PDF/A-dokumentiksi. PDF/A-tiedosto on pitkäaikaissäilytykseen ja arkistointiin tarkoitettu tiedostomuoto."
helpFileBrowse = "Valitse muunnettava PDF-tiedosto Browse…-painikkeella ja klikkaa sen jälkeen Lataa-painiketta, jonka jälkeen kuvailutietolomake avautuu."
helpIntroAlert = "Tiedoston koosta riippuen lataus voi kestää yli minuutin."

helpMetadataIntro = "Voit lisätä halutessasi kuvailutietoja muunnettavalle tiedostolle. Voit jättää myös kuvailutieto-kenttiä tyhjäksi."
helpMetadataPurpose = "Tiedot näkyvät muunnetun tiedoston Dokumentin ominaisuudet -kohdassa. Uudet kuvailutiedot korvaavat aiemmat dokumentin kuvailutiedot. Jos jätät kentän tyhjäksi, aiemmat dokumentin kuvailutiedot jäävät tiedostoon."

helpMetadataProcess = "Muunna tiedosto PDF/A-muotoon klikkaamalla Muunna-painiketta. Lataa tiedosto itsellesi klikkaamalla Lataa-painiketta."

helpConversionReview = "Selaa muunnettu PDF/A-tiedosto läpi huolellisesti ja tarkista, että kaikki teksti- ja kuvaelementit näkyvät tarkoittamallasi tavalla. Kiinnitä huomiota myös tavutukseen."
helpRememberToDelete = "Kun olet ladannut muunnetun tiedoston, voit poistaa sen palvelimelta klikkaamalla Poista-painiketta. Yli vuorokauden vanhat tiedostot poistetaan palvelusta automaattisesti."