; (c) 2017 Technische Universität Berlin
;
; This software is licensed under GNU General Public License version 3 or later.
;
; For the full copyright and license information, 
; please see https://www.gnu.org/licenses/gpl-3.0.html or read 
; the LICENSE.txt file that was distributed with this source code.

htmlTitle = Converter
headline = University of Tampere PDF/A converter
introduction = "Converter is a web service that allows you to convert a regular PDF file into a <a href="https://libguides.tuni.fi/opinnaytteet/pdfa\">PDF/A document</a>. A PDF/A file is a file format intended for long-term preservation and archiving."

navButton[] = Home,,glyphicon-home
navButton[] = Help,help.php,glyphicon-question-sign


selectFile = Select a PDF file to upload:
uploadFile = Upload
browse = Browse

uploadedFile = You have uploaded the following file:
processComment = Please choose the processing type.
deleteMessage = After you have finished processing the file, please remove it from the server.
deleteButton = Remove
downloadLabel = You can now download the file
downloadButton = Download
pdfaValidateMessage = Validate as PDF/A:
pdfaConvertMessage = Convert to PDF/A:
pdfaMetadataMessage = "This information will appear in the Document Properties section of the converted file. The new metadata will replace the existing metadata. If you leave a field blank, the previous metadata will remain in the file."

failMessage = Failure
okMessage = OK 

validateButton = Validate
convertButton = Convert
conversionIdle = Waiting to start conversion.
conversionInProgress = Conversion in progress. You will be able to download the file once it completes.
conversionSuccess = Conversion finished successfully. The processed file is ready for download.
conversionFailed = Conversion failed. Please ask help thesis@tuni.fi.

creatorLabel = "Author(s) separated with ';'"
titleLabel = Title
keywordsLabel = "Keywords separated with ';'"
descriptionLabel = Description

pdfaProcessType[] = --analyze,Validate
pdfaProcessType[] = ,Convert

pdfaLevel[] = 1b
pdfaLevel[] = 1a
pdfaLevel[] = 2b
pdfaLevel[] = 2a
pdfaLevel[] = 3b
pdfaLevel[] = 3a
pdfaLevel[] = 3u

pdfaModus[] = ,Normal 
pdfaModus[] = --forceconversion_reconvert,Reconversion
pdfaModus[] = --forceconversion_pagestoimages,Pages to images
pdfaModus[] = --forceconversion_doctoimages,Docs to images


fileNotChosen = You have to select a PDF file.
fileNotSaved = An error occured: the uploaded file couldn't be saved. Please try again.
xmpFileNotSaved = An error occured: the file with metadata couldn't be saved, the metadata were not integrated in the PDF document.
fileNotFound = An error occured: the uploaded file is missing. Please try again.
fileAlreadyExists = An error occured: the file already exists. Please try again.
fileDeletedMessage = "The file was removed."
fileTooLarge = "An error occured: the file is too large to be converted."
returnValueMessage = Details:
uploadNoPdf = You can only upload PDF files.
downloadFileNotExists = An error occured: the file is missing.

imprint = Imprint
contact = Contact
privacy = Privacy Statement

imprint_link = https://www.tu-berlin.de/servicemenue/impressum/
contact_link = "https://surveys.tuni.fi/lime/137772?lang=en"
privacy_link = https://www.tu-berlin.de/allgemeine_seiten/datenschutz/parameter/en/
logo_link = https://tuni.fi/kirjasto
logo_image = images/TAUfi_logo.png



helpHeadline = "PDF/A Converter"
helpIntroduction = "The converter is a web service that allows you to convert a standard PDF file into a PDF/A document. A PDF/A file format is intended for long-term preservation and archiving."
helpFileBrowse = "Select the PDF file to be converted using the Browse… button and then click the Upload button, after which the metadata form will open."
helpIntroAlert = "Depending on the size of the file, uploading may take more than a minute."

helpMetadataIntro = "You can optionally add metadata to the file being converted. You may also leave the metadata fields empty."
helpMetadataPurpose = "The information will be shown in the Document Properties section of the converted file. The new metadata will replace the document's previous metadata. If you leave a field empty, the document's previous metadata will remain in the file."

helpMetadataProcess = "Convert the file to PDF/A format by clicking the Convert button. Download the file for yourself by clicking the Download button."

helpConversionReview = "Carefully review the converted PDF/A file and check that all text and image elements are displayed as intended. Pay attention to hyphenation as well."
helpRememberToDelete = "After you have downloaded the converted file, you can remove it from the server by clicking the Delete button. Files older than 24 hours are removed from the service automatically."